import { canManage } from "../lib/permissions";
import { useState } from "react";
import { Link, useSearchParams } from "react-router-dom";
import { useApi, label } from "../lib/hooks";
import { useAuth } from "../lib/auth";
import { api } from "../lib/api";
import {
  Alert,
  Heading,
  Field,
  Loading,
  Pagination,
  Badge,
} from "../components/UI";
import OfficerSelect from "../components/OfficerSelect";

export function GeneratedLetters() {
  const { user } = useAuth();
  const [params] = useSearchParams();
  const [page, setPage] = useState(1);
  const [search, setSearch] = useState("");
  const { data, loading, error } = useApi(
    `/generated-letters?page=${page}&officer_id=${params.get("officer_id") || ""}&search=${encodeURIComponent(search)}`,
  );
  return (
    <>
      <Heading
        title="Letters"
        description="Official correspondence, drafts and finalized records."
      >
        {canManage(user) && (
          <>
            <Link className="button secondary" to="/letters/batches">
              Letter batches
            </Link>
            <Link className="button" to="/letters/generate">
              Generate Letter
            </Link>
          </>
        )}
      </Heading>
      <Alert error={error} />
      <section className="panel">
        <Field
          name="search"
          title="Search reference number"
          value={search}
          onChange={(v) => {
            setSearch(v);
            setPage(1);
          }}
        />
        {loading ? (
          <Loading />
        ) : (
          <div className="table-scroll">
            <table>
              <thead>
                <tr>
                  {[
                    "Officer",
                    "Letter Type",
                    "Reference Number",
                    "Date",
                    "Generated By",
                    "Status",
                    "Actions",
                  ].map((v) => (
                    <th key={v}>{v}</th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {data?.data.map((l) => (
                  <tr key={l.id}>
                    <td>{l.officer?.full_name_en}</td>
                    <td>{label(l.letter_batch?.document_type)}</td>
                    <td>{l.ref_no}</td>
                    <td>{l.letter_date?.slice(0, 10)}</td>
                    <td>{l.creator?.name || "—"}</td>
                    <td>
                      <Badge value={l.status} />
                    </td>
                    <td>
                      <div className="actions">
                        {canManage(user) && (
                          <Link to={`/letters/${l.id}/edit`}>
                            {l.status === "final" ? "Details" : "Edit draft"}
                          </Link>
                        )}
                        <a
                          href={`/api/letters/${l.id}/pdf`}
                          target="_blank"
                          rel="noreferrer"
                        >
                          Preview / Print
                        </a>
                        <a href={`/api/letters/${l.id}/pdf?download=1`}>
                          Download
                        </a>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
            {!data?.data.length && <p className="empty">No letters found.</p>}
          </div>
        )}
        <Pagination data={data} onPage={setPage} />
      </section>
    </>
  );
}

export default function GenerateLetter() {
  const [params] = useSearchParams();
  const { user } = useAuth();
  const [values, setValues] = useState({
    document_type: "appointment",
    officer_id: params.get("officer_id") || "",
    letter_date: new Date().toISOString().slice(0, 10),
    my_ref_no: "",
    signatory_id: "",
  });
  const { data: meta } = useApi("/metadata");
  const { data: officer } = useApi(
    values.officer_id ? `/officers/${values.officer_id}` : null,
  );
  const [error, setError] = useState(null);
  const [busy, setBusy] = useState(false);
  const [batchId, setBatchId] = useState(null);
  const [letterId, setLetterId] = useState(null);
  const [finalized, setFinalized] = useState(false);
  const set = (key, v) => {
    setValues({ ...values, [key]: v });
  };
  async function save(e) {
    e.preventDefault();
    setBusy(true);
    setError(null);
    try {
      let id = batchId;
      if (!id) {
        const b = await api("/batches", {
          method: "POST",
          body: {
            name: `${label(values.document_type)} - ${values.my_ref_no}`,
            document_type: values.document_type,
            my_ref_no: values.my_ref_no,
            letter_date: values.letter_date,
            probation_effective_date: values.effective_date || null,
          },
        });
        id = b.id;
        setBatchId(id);
      }
      await api(`/batches/${id}/generate`, {
        method: "POST",
        body: { officer_ids: [Number(values.officer_id)] },
      });
      const batch = await api(`/batches/${id}`);
      const letter = batch.letters.find(
        (l) => Number(l.officer_id) === Number(values.officer_id),
      );
      if (values.signatory_id)
        await api(`/letters/${letter.id}`, {
          method: "PUT",
          body: {
            ref_no: letter.ref_no,
            subject: letter.subject,
            signatory_id: values.signatory_id,
          },
        });
      setLetterId(letter.id);
      setError(null);
    } catch (e) {
      setError(e);
    } finally {
      setBusy(false);
    }
  }
  if (!canManage(user))
    return (
      <Alert
        error={new Error("Letter generation requires administrator access.")}
      />
    );
  return (
    <>
      <Heading
        title="Generate Letter"
        description="Create official letters using approved templates."
      />
      <Alert error={error} />
      <div className="chart-grid">
        <section className="panel">
          <h2>Letter Details</h2>
          <p className="muted">
            Fill in the information below to prepare a draft.
          </p>
          <form onSubmit={save}>
            <fieldset disabled={busy || !!batchId}>
              <Field
                name="document_type"
                title="1. Select Letter Template"
                required
                options={(meta?.document_types || []).map((o) => ({
                  ...o,
                  label: label(o.value),
                }))}
                value={values.document_type}
                onChange={(v) => set("document_type", v)}
              />
              <OfficerSelect
                value={values.officer_id}
                onChange={(v) => set("officer_id", v)}
              />
              <div className="form-grid">
                <Field
                  name="my_ref_no"
                  title="Reference Number"
                  required
                  value={values.my_ref_no}
                  onChange={(v) => set("my_ref_no", v)}
                />
                <Field
                  name="letter_date"
                  title="Letter Date"
                  type="date"
                  required
                  value={values.letter_date}
                  onChange={(v) => set("letter_date", v)}
                />
                <Field
                  name="effective_date"
                  title="Effective Date"
                  type="date"
                  value={values.effective_date}
                  onChange={(v) => set("effective_date", v)}
                />
                <Field
                  name="signatory_id"
                  title="Signatory"
                  options={meta?.signatories || []}
                  value={values.signatory_id}
                  onChange={(v) => set("signatory_id", v)}
                />
              </div>
            </fieldset>
            <p className="muted">
              Save a draft to preview the official PDF, edit its wording and
              copies, and finalize it. Finalizing may update the officer’s
              service record.
            </p>
            <div className="form-footer">
              <Link className="button secondary" to="/letters">
                Cancel
              </Link>
              <button disabled={busy || !!letterId}>
                {busy
                  ? "Preparing…"
                  : batchId
                    ? "Retry draft generation"
                    : "Save Draft & Preview PDF"}
              </button>
            </div>
          </form>
        </section>
        <section className="panel">
          <h2>Letter Preview</h2>
          {letterId && (
            <>
              <iframe
                className="pdf-preview"
                title="Official letter PDF"
                src={`/api/letters/${letterId}/pdf`}
              />
              <div className="actions">
                {!finalized && (
                  <button
                    className="teal"
                    disabled={busy}
                    onClick={async () => {
                      if (
                        !window.confirm(
                          "Finalize and archive this letter? This makes the letter read-only and may update the service record.",
                        )
                      )
                        return;
                      setBusy(true);
                      try {
                        await api(`/letters/${letterId}/finalize`, {
                          method: "POST",
                        });
                        setFinalized(true);
                      } catch (e) {
                        setError(e);
                      } finally {
                        setBusy(false);
                      }
                    }}
                  >
                    Generate Final PDF
                  </button>
                )}
                {finalized && (
                  <span role="status">Letter finalized and archived.</span>
                )}
                <Link
                  className="button secondary"
                  to={`/letters/${letterId}/edit`}
                >
                  {finalized
                    ? "View finalized letter"
                    : "Edit draft and copy recipients"}
                </Link>
                <a
                  className="button teal"
                  href={`/api/letters/${letterId}/pdf`}
                  target="_blank"
                  rel="noreferrer"
                >
                  Preview PDF
                </a>
              </div>
            </>
          )}
          {!letterId && (
            <>
              <p className="muted">
                Layout guide. The saved PDF uses the approved server template.
              </p>
              <article className="letter-paper">
                <header>
                  <strong>DEMOCRATIC SOCIALIST REPUBLIC OF SRI LANKA</strong>
                  <p>Public Service Administration</p>
                </header>
                <p>
                  Ref No: {values.my_ref_no || "—"}
                  <span style={{ float: "right" }}>{values.letter_date}</span>
                </p>
                <h3>{label(values.document_type).toUpperCase()}</h3>
                <p>
                  <strong>
                    {officer?.full_name_en || "Select an officer"}
                  </strong>
                  <br />
                  {officer?.designation}
                  <br />
                  {officer?.ds_division?.name_en}
                  <br />
                  {officer?.district?.name_en}
                </p>
                <p>
                  This correspondence concerns the{" "}
                  {label(values.document_type).toLowerCase()} of the above
                  officer
                  {values.effective_date
                    ? ` with effect from ${values.effective_date}`
                    : ""}
                  .
                </p>
                <p>
                  The official wording, signatory and copy recipients will be
                  populated from the approved template when you prepare the
                  draft.
                </p>
                <p>Yours faithfully,</p>
                <p>
                  {meta?.signatories?.find(
                    (s) => String(s.id) === String(values.signatory_id),
                  )?.officer_name || "Authorized signatory"}
                </p>
              </article>
            </>
          )}
          {letterId && <a href={`/api/letters/${letterId}/pdf`}>Open PDF</a>}
        </section>
      </div>
    </>
  );
}
