import { useState } from "react";
import { useApi, label } from "../lib/hooks";
import { Alert, Heading, Loading, Field } from "../components/UI";
import Icon from "../components/Icon";
import { BarChart, DonutChart } from "../components/Charts";

export function Stats({ data }) {
  return (
    <div className="stats">
      {[
        ["Total Officers", data.total_officers, "officers"],
        ["Active Officers", data.active_officers, "users"],
        ["Documents", data.documents, "documents"],
        ["Letters Generated", data.letters, "letters"],
      ].map(([title, value, icon]) => (
        <article className="panel stat" key={title}>
          <span className="stat-icon">
            <Icon name={icon} size={26} />
          </span>
          <div>
            <p>{title}</p>
            <strong>{Number(value || 0).toLocaleString()}</strong>
            <small>Authorized records</small>
          </div>
        </article>
      ))}
    </div>
  );
}
export function Analytics({ data, full = false }) {
  return (
    <div className="chart-grid">
      <section className="panel">
        <h2>Officers by District</h2>
        <BarChart data={data.districts} />
      </section>
      <section className="panel">
        <h2>Service Status</h2>
        <DonutChart data={data.statuses} />
      </section>
      {full && (
        <>
          <section className="panel">
            <h2>Active vs Retired</h2>
            <DonutChart
              data={[
                { name: "Active", value: data.active_officers },
                {
                  name: "Retired",
                  value:
                    (data.statuses || []).find((s) => s.name === "retired")
                      ?.value || 0,
                },
              ]}
            />
            <small>
              Inactive and unverified accounts are excluded from active totals.
            </small>
          </section>
          <section className="panel">
            <h2>Officers by Grade</h2>
            <DonutChart data={data.grades} />
          </section>
          <section className="panel">
            <h2>Documents by Type</h2>
            <BarChart data={data.document_types} />
          </section>
          <section className="panel">
            <h2>Letters Generated by Month</h2>
            <BarChart data={data.months} line />
          </section>
        </>
      )}
    </div>
  );
}
export default function Reports() {
  const [filters, setFilters] = useState({});
  const { data, loading, error } = useApi(
    `/analytics?${new URLSearchParams(filters)}`,
  );
  const { data: meta } = useApi("/metadata");
  const { data: locations } = useApi(
    `/locations?district_id=${filters.current_district_id || ""}`,
  );
  return (
    <>
      <Heading
        title="Reports & Analytics"
        description="Explore officer, document and correspondence statistics."
      >
        {["xlsx", "pdf"].map((format) => (
          <a
            className={`button ${format === "xlsx" ? "teal" : "secondary"}`}
            key={format}
            href={`/api/analytics?${new URLSearchParams({ ...filters, export: format })}`}
          >
            Export {format === "xlsx" ? "Excel" : "PDF"}
          </a>
        ))}
      </Heading>
      <section className="panel">
        <div className="filters-grid">
          {[
            ["from", "From", "date"],
            ["to", "To", "date"],
            ["current_district_id", "District", "select", locations?.districts],
            [
              "current_ds_division_id",
              "DS Division",
              "select",
              locations?.ds_divisions,
            ],
            ["designation", "Designation"],
            ["current_grade", "Grade", "select", meta?.grades],
            ["service_status", "Status", "select", meta?.service_statuses],
          ].map(([name, title, type, options]) => (
            <Field
              key={name}
              name={name}
              title={title}
              type={type || "text"}
              options={type === "select" ? options || [] : undefined}
              value={filters[name]}
              onChange={(v) =>
                setFilters({
                  ...filters,
                  [name]: v,
                  ...(name === "current_district_id"
                    ? { current_ds_division_id: "" }
                    : {}),
                })
              }
            />
          ))}
        </div>
        <p className="muted">
          Officer totals reflect current records. Date range applies to issued
          documents and finalized letters.
        </p>
        <button className="secondary" onClick={() => setFilters({})}>
          Reset filters
        </button>
      </section>
      <Alert error={error} />
      {loading ? (
        <Loading />
      ) : (
        data && (
          <>
            <Stats data={data} />
            <Analytics data={data} full />
            <section className="panel">
              <h2>Report Summary</h2>
              <div className="table-scroll">
                <table>
                  <thead>
                    <tr>
                      <th>Report</th>
                      <th>Category</th>
                      <th>Total</th>
                    </tr>
                  </thead>
                  <tbody>
                    {[
                      ["Officers by District", "districts"],
                      ["Officers by Grade", "grades"],
                      ["Documents by Type", "document_types"],
                      ["Letters by Month", "months"],
                    ].flatMap(([title, key]) =>
                      (data[key] || []).map((row) => (
                        <tr key={`${key}-${row.name}`}>
                          <td>{title}</td>
                          <td>{label(row.name)}</td>
                          <td>{row.value}</td>
                        </tr>
                      )),
                    )}
                  </tbody>
                </table>
              </div>
            </section>
          </>
        )
      )}
    </>
  );
}
