<?php

namespace App\Filament\Resources;

use BackedEnum;
use UnitEnum;
use App\Enums\DocumentType;
use App\Filament\Resources\DocumentResource\Pages;
use App\Models\Document;
use Filament\Forms\Components\DatePicker;
use Filament\Schemas\Components\Grid;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\TextInput;
use Filament\Resources\Resource;
use Filament\Schemas\Schema;
use Filament\Actions\EditAction;
use Filament\Actions\ViewAction;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Filters\SelectFilter;
use Filament\Tables\Table;
use Illuminate\Support\Facades\Storage;

class DocumentResource extends Resource
{
    protected static ?string $model = Document::class;

    protected static string | BackedEnum | null $navigationIcon = 'heroicon-o-document-text';

    protected static string | UnitEnum | null $navigationGroup = 'Personnel';

    public static function form(Schema $schema): Schema
    {
        return $schema->components([
            Grid::make(2)->components([
                Select::make('officer_id')
                    ->relationship('officer', 'full_name_en')
                    ->searchable()
                    ->preload()
                    ->required(),
                Select::make('document_type')
                    ->options(collect(DocumentType::cases())->mapWithKeys(fn ($d) => [$d->value => $d->label()]))
                    ->required(),
                TextInput::make('ref_no')->maxLength(100),
                DatePicker::make('issue_date'),
                TextInput::make('file_path')->label('File Path')->disabled(),
                Select::make('generated_by')->relationship('generator', 'name')->disabled(),
            ]),
        ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                TextColumn::make('officer.full_name_en')->label('Officer')->searchable()->sortable(),
                TextColumn::make('document_type')->badge()->formatStateUsing(fn (DocumentType $state) => $state->label()),
                TextColumn::make('ref_no')->searchable(),
                TextColumn::make('issue_date')->date()->sortable(),
                TextColumn::make('generator.name')->label('Generated By')->toggleable(),
            ])
            ->filters([
                SelectFilter::make('document_type')
                    ->options(collect(DocumentType::cases())->mapWithKeys(fn ($d) => [$d->value => $d->label()])),
            ])
            ->defaultSort('issue_date', 'desc')
            ->recordActions([
                ViewAction::make()
                    ->url(fn (Document $record) => $record->file_path
                        ? Storage::disk('local')->url($record->file_path)
                        : null)
                    ->openUrlInNewTab(),
                EditAction::make(),
            ]);
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListDocuments::route('/'),
            'create' => Pages\CreateDocument::route('/create'),
            'edit' => Pages\EditDocument::route('/{record}/edit'),
        ];
    }
}
