export const resources = {
  officers: {
    title: "Officers",
    description: "Manage officer profiles and verify new registrations.",
    columns: ["full_name_en", "nic_no", "current_grade", "service_status"],
    fields: [
      ["nic_no", "NIC number", "text", true],
      ["full_name_en", "Full name (English)", "text", true],
      ["full_name_si", "Full name (Sinhala)"],
      ["full_name_ta", "Full name (Tamil)"],
      ["dob", "Date of birth", "date"],
      ["gender", "Gender", "gender", true],
      ["medium", "Language", "medium", true],
      ["current_grade", "Grade", "grades", true],
      ["service_status", "Service status", "service_statuses", true],
      ["confirmation_status", "Confirmation status", "confirmation"],
      ["current_district_id", "District", "districts", true],
      ["current_ds_division_id", "DS division", "ds_divisions", true],
      ["current_gn_division_id", "GN division", "gn_divisions"],
      ["address_line1", "Address line 1"],
      ["address_line2", "Address line 2"],
      ["address_line3", "Address line 3"],
      ["first_appointment_date", "First appointment date", "date"],
      ["appointment_date", "Appointment date", "date"],
      ["confirmation_date", "Confirmation date", "date"],
    ],
  },
  documents: {
    title: "Documents",
    description: "Find and manage archived officer documents.",
    columns: ["officer", "document_type", "ref_no", "issue_date"],
    fields: [
      ["officer_id", "Officer", "officers", true],
      ["document_type", "Document type", "document_types", true],
      ["ref_no", "Reference number"],
      ["issue_date", "Issue date", "date", true],
      ["file", "PDF document", "file"],
    ],
  },
  "service-histories": {
    title: "Service history",
    description:
      "Appointments, promotions, transfers, and other service events.",
    columns: ["officer", "event_type", "ref_no", "effective_date"],
    fields: [
      ["officer_id", "Officer", "officers", true],
      ["event_type", "Event type", "event_types", true],
      ["ref_no", "Reference number"],
      ["effective_date", "Effective date", "date", true],
      ["description", "Description", "textarea"],
      ["old_value", "Previous value"],
      ["new_value", "New value"],
    ],
  },
  signatories: {
    title: "Signatories",
    description: "Manage authorized signatories and their jurisdictions.",
    columns: ["officer_name", "designation", "category", "is_active"],
    fields: [
      ["officer_name", "Name", "text", true],
      ["designation", "Designation", "text", true],
      ["category", "Category", "categories", true],
      ["district_id", "District", "districts"],
      ["ds_division_id", "DS division", "ds_divisions"],
      ["is_active", "Active", "checkbox"],
      ["file", "Signature image (PNG or JPG)", "file"],
    ],
  },
  users: {
    title: "Users",
    description: "Manage accounts, access levels, and account status.",
    columns: ["name", "email", "role", "status"],
    fields: [
      ["name", "Full name", "text", true],
      ["email", "Email", "email", true],
      ["nic_no", "NIC number"],
      ["phone", "Phone"],
      ["password", "Password (leave blank to keep existing)", "password"],
      ["role", "Role", "roles", true],
      ["status", "Account status", "statuses", true],
      ["district_id", "District", "districts"],
      ["ds_division_id", "DS division", "ds_divisions"],
    ],
  },
};
export const staticOptions = {
  gender: [
    { value: "male", label: "Male" },
    { value: "female", label: "Female" },
  ],
  medium: [
    { value: "si", label: "Sinhala" },
    { value: "ta", label: "Tamil" },
    { value: "en", label: "English" },
  ],
  confirmation: [
    { value: "pending", label: "Pending" },
    { value: "confirmed", label: "Confirmed" },
  ],
};
